export const EVENTS_NAMES: string[] = [
   'click',
   'keyup',
   'change',
   'input',
   'mouseout',
   'mouseover',
   'mouseenter',
   'mouseleave',
   'mousedown',
   'mouseup',
   'scroll',
   'mousewheel',
   'submit',
   'focus',
   'blur',
   'dragstart',
   'dragend'
];